use winit::keyboard::{KeyCode, PhysicalKey};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Left,
    Right,
    Up,
    Down,
    PageUp,
    PageDown,
    Back,
    Return,
    Escape,
    Slash,
    LBracket,
    RBracket,
    Equals,
}

impl Key {
    pub fn from_physical_key(key: PhysicalKey) -> Option<Self> {
        let PhysicalKey::Code(code) = key else {
            return None;
        };
        Some(match code {
            KeyCode::KeyA => Self::A,
            KeyCode::KeyB => Self::B,
            KeyCode::KeyC => Self::C,
            KeyCode::KeyD => Self::D,
            KeyCode::KeyE => Self::E,
            KeyCode::KeyF => Self::F,
            KeyCode::KeyG => Self::G,
            KeyCode::KeyH => Self::H,
            KeyCode::KeyI => Self::I,
            KeyCode::KeyJ => Self::J,
            KeyCode::KeyK => Self::K,
            KeyCode::KeyL => Self::L,
            KeyCode::KeyM => Self::M,
            KeyCode::KeyN => Self::N,
            KeyCode::KeyO => Self::O,
            KeyCode::KeyP => Self::P,
            KeyCode::KeyQ => Self::Q,
            KeyCode::KeyR => Self::R,
            KeyCode::KeyS => Self::S,
            KeyCode::KeyT => Self::T,
            KeyCode::KeyU => Self::U,
            KeyCode::KeyV => Self::V,
            KeyCode::KeyW => Self::W,
            KeyCode::KeyX => Self::X,
            KeyCode::KeyY => Self::Y,
            KeyCode::KeyZ => Self::Z,
            KeyCode::Digit0 => Self::Key0,
            KeyCode::Digit1 => Self::Key1,
            KeyCode::Digit2 => Self::Key2,
            KeyCode::Digit3 => Self::Key3,
            KeyCode::Digit4 => Self::Key4,
            KeyCode::Digit5 => Self::Key5,
            KeyCode::Digit6 => Self::Key6,
            KeyCode::Digit7 => Self::Key7,
            KeyCode::Digit8 => Self::Key8,
            KeyCode::Digit9 => Self::Key9,
            KeyCode::ArrowLeft => Self::Left,
            KeyCode::ArrowRight => Self::Right,
            KeyCode::ArrowUp => Self::Up,
            KeyCode::ArrowDown => Self::Down,
            KeyCode::PageUp => Self::PageUp,
            KeyCode::PageDown => Self::PageDown,
            KeyCode::Backspace => Self::Back,
            KeyCode::Enter | KeyCode::NumpadEnter => Self::Return,
            KeyCode::Escape => Self::Escape,
            KeyCode::Slash | KeyCode::NumpadDivide => Self::Slash,
            KeyCode::BracketLeft => Self::LBracket,
            KeyCode::BracketRight => Self::RBracket,
            KeyCode::Equal | KeyCode::NumpadEqual => Self::Equals,
            _ => return None,
        })
    }
}
